
EHZ_SUCCEED_CODE=0
EHZ_SUCCEED_MSG="succeed"

WEB_SERVER_EXCEPTION_ERRNO=-10002
WEB_SERVER_EXCEPTION_MSG="web service fault"

SOAP_INTERFACE_EXCEPTION_ERRNO=-10001
SOAP_INTERFACE_EXCEPTION_MSG="soap interface exception"

SOAP_INTERFACE_REQUEST_DARA_ERRNO=-10003
SOAP_INTERFACE_REQUEST_EXCEPTION_MSG="soap request xml format error"

SOAP_SERVICE_NOT_FIND_ERRNO = -10004
SOAP_SERVICE_NOT_FIND_MSG="webservice interface not find"

PLAT_VERSION="v1.1.10"
